In [1]:
try:
    print(h)
except:
    print("hello")
else:
    print("hi")
finally:
    print("thank you")

hello
thank you

In [5]:
try:
    print("h")
except:
   print("hello")
else:
    print("hi")
finally:
    print("thank you")

h
hi
thank you

In [17]:
try:
    a=1
    print("h")
except:
    print(" hello")
else:
    print("hi")

h
hi

In [10]:
try:
    print("h")
except:
    a=1 
     print(" hello")
else:
    print("hi")

IndentationError: unexpected indent (2052252035.py, line 5)

In [11]:
a=10
b=2
if a/b:
    raise zeroDivisionError("name")

NameError: name 'zeroDivisionError' is not defined

In [13]:
a=10
b=2
if a/b:
    raise nameError("name")

NameError: name 'nameError' is not defined

In [19]:
def fact(n):
    if n<=0:
        return 1
    return (n*fact(n-1))
print(fact(6))

720

In [7]:
try:
    num1 = int(input("enter a num1:"))
    num2 = int(input("enter a num2:"))
    result = num1/num2
except:
    print("zero division error")

else:
    print(result)
finally:
    print("thank you")

enter a num1: 5
enter a num2: 4

1.25
thank you

In [5]:
try:
    num1 = int(input("enter a num1:"))
    num2 = int(input("enter a num2:"))
    result = num1/num2
except:
    print("zero division error")
else:
    print(result)

enter a num1: 5
enter a num2: 0

zero division error

In [6]:
class ExampleClass:
    def __init__(self, data,divisor):
        self.data = data
        self.divisor=divisor

    def divide(self):
        try:
            result = self.data / self.divisor
        except :
            result = None
        else:
            print("Division successful!")
        finally:
            print("Execution completed.")
        
        return result
data=int(input("enter a num"))
divisor=int(input("enter a num2"))
example = ExampleClass(data,divisor)
print(example.divide())

enter a num 5
enter a num2 5

Division successful!
Execution completed.
1.0

In [8]:
df=open(r"C:\Users\gnana\OneDrive\Desktop\py-ds\mip-py.txt","w")

In [9]:
df.write("hello")

5

In [10]:
df = open(r"C:\Users\gnana\Downloads\Tamil_movies_dataset.csv","r")

In [11]:
df.read()

'MovieName,Genre,Rating,Director,Actor,PeopleVote,Year,Hero_Rating,movie_rating,content_rating\nMouna Guru,Action,7.7,Santha Kumar,Arulnithi,746,2011,8,8,7.9\n7 Aum Arivu,Action,6.2,A.R. Murugadoss,Suriya,9479,2011,9,9,8.066666667\nVaagai Sooda Vaa,Comedy,8,A. Sarkunam,Vimal,14522,2011,8,7,7.666666667\nMankatha,Action,7.6,Venkat Prabhu,Ajith Kumar,12276,2011,6,8,7.2\nKanchana: Muni 2,Comedy,6.5,Lawrence Raghavendra,Lawrence Raghavendra,1044,2011,8,9,7.833333333\nDeiva Thirumagal,Drama,8.1,A.L. Vijay,Vikram,44517,2011,9,9,8.7\nVaanam,Action,7.2,Radha Krishna Jagarlamudi,T.R. Silambarasan,1307,2011,7,8,7.4\nKo,Action,7.8,K.V. Anand,Jiiva,4759,2011,9,7,7.933333333\nPayanam,Action,7.3,Radha Mohan,Nagarjuna Akkineni,677,2011,6,8,7.1\nYutham Sei,Crime,8,Myshkin,Cheran,1678,2011,4,9,7\nAadukalam,Action,8.1,Vetrimaaran,Dhanush,4456,2011,8,9,8.366666667\nNaduvula Konjam Pakkatha Kaanom,Comedy,8.2,Balaji Tharaneetharan,Vijay Sethupathi,4530,2012,7,8,7.733333333\nThuppakki,Action,7.9,A.R. Murugadoss,Joseph Vijay,22577,2012,9,9,8.633333333\nPizza,Horror,8,Karthik Subbaraj,Vijay Sethupathi,6528,2012,2,8,6\nNaan,Crime,7.5,Jeeva Shankar,Vijay Antony,1365,2012,3,7,5.833333333\nThe Fly,Action,7.7,S.S. Rajamouli,J.V.V. Sathyanarayana,20590,2012,5,7,6.566666667\nKalakalappu,Comedy,6.9,Sundar C.,Vimal,1019,2012,7,8,7.3\nVazhakku Enn 18/9,Crime,8.3,Balaji Sakthivel,Sri,1915,2012,5,9,7.433333333\nKumki,Drama,7,Prabu Solomon,Vikram Prabhu,1231,2012,8,9,8\nNeethaane En Ponvasantham,Romance,6.5,Gautham Vasudev Menon,Jiiva,1500,2012,9,8,7.833333333\nThalaimuraigal,Drama,7.6,Balu Mahendra,Karthick,40034,2013,8,7,7.533333333\nBiriyani,Action,5.7,Venkat Prabhu,Karthi,1272,2013,7,8,6.9\nIvan Veramaathiri,Action,6,M. Saravanan,Vikram Prabhu,290,2013,4,9,6.333333333\nKalyana Samayal Saadham,Comedy,7.1,R.S. Prasanna,Prasanna,117,2013,5,8,6.7\nIrandam Ulagam,Action,5.7,K. Selvaraghavan,Arya,1101,2013,8,8,7.233333333\nPandiya Naadu,Action,7.2,Suseenthiran,Vishal,1168,2013,9,8,8.066666667\nArrambam,Action,7,Vishnuvardhan,Ajith Kumar,8415,2013,6,9,7.333333333\nOnaayum Aattukkuttiyum,Action,8.2,Myshkin,Myshkin,2181,2013,8,8,8.066666667\nRaja Rani,Comedy,7.6,Atlee Kumar,Arya,4088,2013,9,9,8.533333333\n6 Candles,Thriller,7,V.Z. Dhorai,Sandra Amy,16247,2013,4,9,6.666666667\nMoodar Koodam,Comedy,7.7,Naveen,Naveen,1081,2013,5,8,6.9\nVaruthapadatha Valibar Sangam,Comedy,6.7,Ponram,Sivakarthikeyan,1352,2013,6,8,6.9\nThanga Meengal,Drama,7.9,Ram,Ram,791,2013,4,9,6.966666667\nAadhalal Kadhal Seiveer,Romance,7.2,Suseenthiran,Santhosh Ramesh,62323,2013,5,8,6.733333333\nMaryan,Adventure,7.1,Ganapathy Bharat,Dhanush,2761,2013,6,9,7.366666667\nSingam 2,Action,6.3,Hari,Suriya,5369,2013,8,9,7.766666667\nTheeya Velai Seiyyanum Kumaru,Comedy,6.1,Sundar C.,Siddharth,1320,2013,7,8,7.033333333\nNeram,Action,7.5,Alphonse Puthren,Nivin Pauly,4292,2013,5,8,6.833333333\nSoodhu Kavvum,Comedy,8.3,Nalan Kumarasamy,Vijay Sethupathi,8307,2013,6,9,7.766666667\nEthir Neechal,Comedy,6.8,R.S. Durai Senthilkumar,Sivakarthikeyan,1747,2013,8,9,7.933333333\nKedi Billa Killadi Ranga,Comedy,5.5,Pandiraj,Vimal,578,2013,7,7,6.5\nParadesi,Drama,8,Bala,Atharvaa Murali,1644,2013,8,8,8\nKaakkaa Muttai,Comedy,8.4,M. Manikandan,Ramesh,5011,2014,9,7,8.133333333\nKayal,Romance,6.4,Prabu Solomon,Chandran,320,2014,8,8,7.466666667\nPisasu,Horror,7.6,Myshkin,Naga,1658,2014,7,9,7.866666667\nLingaa,Action,5.6,K.S. Ravikumar,Rajinikanth,4807,2014,4,8,5.866666667\nKaaviya Thalaivan,Drama,7.6,Vasanthabalan,Siddharth,1133,2014,5,7,6.533333333\nKaththi,Action,7.9,A.R. Murugadoss,Joseph Vijay,16760,2014,8,7,7.633333333\nJeeva,Drama,7.5,Suseenthiran,Vishnu Vishal,944,2014,9,9,8.5\nMadras,Action,8,Pa. Ranjith,Karthi,3102,2014,8,8,8\nKathai Thiraikathai Vasanam Iyakkam,Drama,6.8,Parthiban,Thambi Ramaiah,586,2014,7,7,6.933333333\nJigarthanda,Action,8.3,Karthik Subbaraj,Siddharth,9578,2014,8,7,7.766666667\nVelaiilla Pattadhari,Action,7.8,Velraj,Dhanush,5039,2014,9,8,8.266666667\nSathuranga Vettai,Crime,8.1,H. Vinoth,Nataraja Subramanian,2409,2014,8,9,8.366666667\nSaivam,Drama,6.8,A.L. Vijay,Nassar,59767,2014,7,9,7.6\nMundaasupatti,Comedy,7.6,Ram Kumar,Vishnu Vishal,1118,2014,4,8,6.533333333\nKochadaiiyaan,Animation,6.3,Soundarya R. Ashwin,Rajinikanth,4692,2014,5,8,6.433333333\nVaayai Moodi Pesavum,Comedy,6.7,Balaji Mohan,Dulquer Salmaan,1448,2014,9,9,8.233333333\nCuckoo,Drama,7.8,Raju Murugan,Dinesh,617,2014,8,7,7.6\nThegidi,Crime,7.8,P. Ramesh,Ashok Selvan,27868,2014,7,8,7.6\nPannaiyarum Padminiyum,Comedy,7.8,S.U. Arun Kumar,Vijay Sethupathi,1375,2014,5,9,7.266666667\nGoli Soda,Action,7.7,Vijay Milton,Kishore Kumar G.,905,2014,8,7,7.566666667\nVeeram,Action,6.5,Siva,Ajith Kumar,6655,2014,9,7,7.5\nRajini Murugan,Action,5.7,Ponram,Sivakarthikeyan,1322,2015,6,8,6.566666667\nVisaaranai,Crime,8.5,Vetrimaaran,Dinesh,6219,2015,8,9,8.5\nPasanga 2,Drama,7.5,Pandiraj,Suriya,1031,2015,7,7,7.166666667\nThoongaavanam,Action,7,Rajesh M. Selva,Kamal Haasan,1819,2015,5,8,6.666666667\nNaanum Rowdy Thaan,Action,7.3,Vignesh Shivan,Vijay Sethupathi,3354,2015,8,9,8.1\nKuttram Kadithal,Drama,8,Bramma G.,Master Ajay,665,2015,4,8,6.666666667\nKirumi,Crime,7,Anu Charan,Anucharan,45686,2015,7,7,7\nMaya,Horror,7.6,Ashwin Saravanan,Nayanthara,1302,2015,9,8,8.2\nThani Oruvan,Action,8.4,Mohan Raja,Jayam Ravi,15421,2015,6,8,7.466666667\nPapanasam,Drama,8.4,Jeethu Joseph,Kamal Haasan,5295,2015,8,7,7.8\nIndru Netru Naalai,Comedy,8,R. Ravikumar,Vishnu Vishal,3339,2015,5,9,7.333333333\nDemonte Colony,Horror,6.9,R. Ajay Gnanamuthu,Arulnithi,1725,2015,8,9,7.966666667\n36 Vayadhinile,Drama,7.1,Roshan Andrews,Jyotika,647,2015,5,8,6.7\nUttama Villain,Comedy,7.2,Ramesh Aravind,Kamal Haasan,2561,2015,7,7,7.066666667\nKanchana 2,Comedy,5.5,Lawrence Raghavendra,Lawrence Raghavendra,1261,2015,8,8,7.166666667\nOK Kanmani,Romance,7.4,Mani Ratnam,Dulquer Salmaan,4611,2015,6,9,7.466666667\nRajathandhiram,Action,7.7,A.G. Amid,Veera Bahu,1154,2015,3,8,6.233333333\nEnakkul Oruvan,Thriller,7.7,Prasad Ramar,Siddharth,1456,2015,2,7,5.566666667\nPress 1 for Tamil,Comedy,7,Ramprakash Rayappa,Nakhul,850,2015,4,8,6.333333333\nYennai Arindhaal,Action,7.3,Gautham Vasudev Menon,Ajith Kumar,7740,2015,7,9,7.766666667\nI,Action,7.3,S. Shankar,Vikram,18345,2015,8,9,8.1\nDhuruvangal Pathinaaru,Action,8.4,Karthick Naren,Rahman,10895,2016,5,8,7.133333333\nChennai 600028 Second Innings,Comedy,7,Venkat Prabhu,Jai,937,2016,1,7,5\nAchcham Yenbadhu Madamaiyada,Action,6.4,Gautham Vasudev Menon,T.R. Silambarasan,1896,2016,6,7,6.466666667\nAmmani,Drama,7.9,Lakshmi Ramakrishnan,Semmalar Annam,52730,2016,9,7,7.966666667\nAandavan Kattalai,Drama,8.1,M. Manikandan,Vijay Sethupathi,2060,2016,8,8,8.033333333\nKuttrame Thandanai,Crime,7.8,M. Manikandan,Vidharth,60939,2016,7,7,7.266666667\nDharmadurai,Drama,7.5,Seenu Ramasamy,Vijay Sethupathi,1568,2016,8,9,8.166666667\nJoker,Comedy,8.4,Raju Murugan,Raju Saravanan,2830,2016,5,9,7.466666667\nKabali,Action,6.2,Pa. Ranjith,Rajinikanth,11149,2016,8,8,7.4\nMetro,Action,7.3,Ananda Krishnan,Shirish,697,2016,5,9,7.1\nIraivi,Crime,8,Karthik Subbaraj,S.J. Suryah,2736,2016,9,8,8.333333333\nUriyadi,Action,8.1,Vijay Kumar,Vijay Kumar,1878,2016,8,7,7.7\n24,Action,7.8,Vikram K. Kumar,Suriya,15774,2016,7,8,7.6\nTheri,Action,7.1,Atlee Kumar,Joseph Vijay,12365,2016,8,9,8.033333333\nOopiri,Comedy,8,Vamshi Paidipally,Nagarjuna Akkineni,3915,2016,9,9,8.666666667\nKadhalum Kadanthu Pogum,Comedy,7.3,Nalan Kumarasamy,Vijay Sethupathi,2407,2016,8,8,7.766666667\nPichaikkaran,Action,7.6,Sasi,Vijay Antony,1437,2016,7,9,7.866666667\nSaala Khadoos,Action,7.6,Sudha Kongara,Madhavan,10941,2016,8,8,7.866666667\nCrime 23,Action,7.4,Arivazhagan Venkatachalam,Arun Vijay,1915,2017,4,9,6.8\nMuthuramalingam,Action,1.6,Rajadurai,Priya Anand,14063,2017,5,9,5.2\nDream Factory,Drama,6.7,Arun Chidambaram,Jiya Anil Manne,124,2017,6,8,6.9\nYaman,Action,6.2,Jeeva Shankar,Vijay Antony,454,2017,9,8,7.733333333\nEnnodu Vilayadu,Thriller,5.6,Arun Krishnaswami,Bharath Srinivasan,77,2017,8,7,6.866666667\nKadhal Kan Kattudhe,Drama,6.5,Shivaraj,Aneeruth,30623,2017,7,8,7.166666667\nPagadi Aattam,Crime,5.8,Ram K. Chandran,Rahman,79,2017,4,9,6.266666667\nRum,Horror,4.2,Sai Bharath,Arjun Chidambaram,118,2017,5,9,6.066666667\nSingam 3,Action,6.3,Hari,Suriya,5063,2017,8,8,7.433333333\nBogan,Action,6.4,Lakshman,Jayam Ravi,1358,2017,9,8,7.8\nEnakku Vaaitha Adimaigal,Comedy,5.8,Mahendran Rajamani,Jai,399,2017,8,7,6.933333333\nKoditta Idangalai Nirappuga,Comedy,6.4,Parthiban,Shanthnu Bhagyaraj,65921,2017,7,8,7.133333333\nAdhe Kangal,Action,7.3,Rohin Venkatesan,R. Aravindraj,961,2017,4,9,6.766666667\nBairavaa,Action,5.9,Bharathan,Joseph Vijay,7376,2017,5,9,6.633333333\nLens,Drama,6.9,Jayaprakash Radhakrishnan,Anand Sami,942,2017,8,8,7.633333333\nAruvi,Drama,8.6,Arun Prabhu Purushothaman,Aditi Balan,9890,2017,7,7,7.533333333\nUlkuththu,Thriller,6.7,Caarthick Raju,Dr. Chef Damodaran,17655,2017,9,8,7.9\nBalloon,Horror,4.6,Sinish,Anjali,274,2017,5,9,6.2\nKalavaadiya Pozhuthugal,Romance,6.1,Thangar Bachan,Bhoomika Chawla,48,2017,8,8,7.366666667\nVelaikkaran,Action,7.3,Mohan Raja,Sivakarthikeyan,2984,2017,6,7,6.766666667\nSakka Podu Podu Raja,Action,4.2,G.L. Sethuraman,Aryan,357,2017,9,8,7.066666667\nBhrama.com,Action,5.1,P.S. Vijayakumar,Bhagyaraj,64,2017,7,9,7.033333333\nChennai 2 Singapore,Comedy,6.1,Abbas Akbaar,Abbas Akbar,137,2017,8,8,7.366666667\n12-12-1950,Comedy,5.4,Selvaah,Yogi Babu,69977,2017,8,7,6.8\nKodiveeran,Action,4.8,M. Muthaiya,Gnanasambandam,117,2017,9,8,7.266666667\nRichie,Action,5.3,Gautham Ramachandran,Nivin Pauly,706,2017,9,9,7.766666667\nAnnadurai,Action,5.3,G. Srinivasan,Vijay Antony,213,2017,7,8,6.766666667\nThiruttu Payale 2,Thriller,6.7,Susi Ganesan,Bobby Simha,658,2017,8,9,7.9\nEnglish Padam,Comedy,1.2,Kumaresh Kumar,Sreeja Das,24,2017,4,8,4.4\nIndrajith,Action,3.3,Kalaprabhu Thanu,Gautham Karthik,150,2017,5,8,5.433333333\nEn Aaloda Seruppa Kaanom,Comedy,5,Jagan,K.P. Jagan,61,2017,8,9,7.333333333\nTheeran Adhigaram Ondru,Action,8.2,H. Vinoth,Karthi,8685,2017,4,8,6.733333333\nC/o Surya,Action,5.6,Suseenthiran,Sundeep Kishan,175,2017,7,9,7.2\nIppadai Vellum,Action,5.7,Gaurav Narayanan,Udhayanidhi Stalin,272,2017,8,8,7.233333333\nAramm,Drama,7.8,Gopi Nainar,Nayanthara,1411,2017,5,7,6.6\nThe House Next Door,Horror,6.8,Milind Rau,Prakash Belawadi,1854,2017,8,7,7.266666667\nVizhithiru,Drama,5.9,Meera Kathiravan,Abhinaya,103,2017,9,8,7.633333333\nKadaisi Bench Karthi,Comedy,4.1,Ravee Paargavan,Gnanasambandam,36,2017,8,9,7.033333333\nMersal,Action,7.7,Atlee Kumar,Joseph Vijay,23383,2017,8,8,7.9\nMeyaadha Maan,Romance,7.2,Rathna Kumar,Vaibhav Reddy,870,2017,8,7,7.4\nSolo,Action,7.1,Bejoy Nambiar,Dulquer Salmaan,2772,2017,4,8,6.366666667\nHara Hara Mahadevaki,Comedy,5.3,Santhosh P. Jayakumar,Kovai Babu,450,2017,7,9,7.1\nKaruppan,Action,5.6,R. Panneerselvam,Sami Rajalingam,520,2017,5,8,6.2\nSpyder,Action,6.6,A.R. Murugadoss,Mahesh Babu,8652,2017,7,7,6.866666667\nBayama Irukku,Comedy,5.3,Jawahar,Santhosh Prathap,70,2017,3,8,5.433333333\nAayirathil Iruvar,Action,4.6,Saran,Vinay Rai,57587,2017,5,9,6.2\nKalavu Thozhirchalai,Thriller,5.9,T Krishna Samy,T. Krishnasamy,25,2017,6,8,6.633333333\nVeedevadu,Thriller,5.5,Tatineni Satya,Esha Gupta,44,2017,2,7,4.833333333\nThupparivaalan,Action,7.5,Myshkin,Vishal,3405,2017,8,8,7.833333333\nKathanayagan,Comedy,4.2,Tha. Muruganatham,Meera Krishna,30228,2017,7,9,6.733333333\nNeruppu Da,Action,4.3,Nikki Galrani,Nagineedu,10330,2017,8,9,7.1\nKurangu Bommai,Drama,8.1,Nithilan,Vidharth,1093,2017,7,8,7.7\nMaayavan,Action,7.3,C.V. Kumar,Sundeep Kishan,1468,2017,2,9,6.1\nPuriyaatha Puthir,Thriller,6.6,Ranjit Jeyakodi,Vijay Sethupathi,771,2017,8,9,7.866666667\nVivegam,Action,5.6,Siva,Ajith Kumar,10389,2017,9,8,7.533333333\nThappu Thanda,Crime,6,Srikantan,Ajay Ghosh,42,2017,7,8,7\nTaramani,Drama,7.5,Ram,Anjali,1252,2017,4,7,6.166666667\nVelaiyilla Pattathari 2,Action,5.4,Soundarya R. Ashwin,Riaz Ahmed,1783,2017,8,8,7.133333333\nPodhuvaga En Manasu Thangam,Comedy,3.8,Thalapathy Prabhu,Parthiban,115,2017,5,9,5.933333333\nKootathil Oruthan,Comedy,6.7,T.J. Gnanavel,Ashok Selvan,363,2017,7,8,7.233333333\nNibunan,Action,6.6,Arun Vaidyanathan,Varalaxmi Sarathkumar,782,2017,4,9,6.533333333\nMeesaya murukku,Biography,7.6,Hiphop Tamizha Adhi,Hiphop Tamizha Adhi,1869,2017,8,9,8.2\nVikram Vedha,Action,8.7,Gayatri,Pushkar,23249,2017,9,8,8.566666667\nRubaai,Action,6.1,M. Anbazhagan,Anandhi,41952,2017,8,7,7.033333333\nMagalir Mattum,Drama,6.3,Bramma G.,Jyotika,455,2017,9,7,7.433333333\nPandigai,Action,6.5,Feroz,Kreshna,245,2017,7,8,7.166666667\nThiri,Drama,5.2,Ashok Amritharaj S.,A.L. Azhagappan,33926,2017,8,9,7.4\nGemini Ganesanum Suruli Rajanum,Comedy,5.8,Ilavarasu Odam,Regina Cassandra,387,2017,9,9,7.933333333\nChennaiyil Oru Naal 2,Thriller,4.6,Jpr,Sarath Kumar,84,2017,7,8,6.533333333\nIvan Thanthiran,Action,6.3,R. Kannan,RJ Balaji,28334,2017,8,7,7.1\nAdhagappattathu Magajanangalay,Comedy,5,Inba Sekhar,Inbasekhar,19592,2017,9,7,7\nYaanum Theeyavan,Action,6.1,Prashanth G Sekr,Prashanth G Sekar,26862,2017,8,8,7.366666667\nVanamagan,Action,5.5,A.L. Vijay,Arjun,599,2017,7,9,7.166666667\nAnbanavan Asaradhavan Adangadhavan,Action,2.3,Adhik Ravichandran,Tamannaah Bhatia,510,2017,5,9,5.433333333\nMaragatha Nananya,Adventure,7,Ark Saravan,Aadhi,1144,2017,8,7,7.333333333\nUru,Thriller,5.9,Vicky Anand,Vicky Anand,275,2017,8,8,7.3\nPeechaankai,Comedy,6.5,Ashok,Rskarthiik,53,2017,3,8,5.833333333\nRangoon,Action,7.1,Rajkumar Periasamy,Gautham Karthik,560,2017,8,7,7.366666667\nSathriyan,Action,4.8,Vikram Prabhu,Manjima Mohan,51758,2017,7,8,6.6\nBongu,Crime,5.3,Taj,Pooja Bisht,93,2017,8,7,6.766666667\nOru Kidayin Karunai Manu,Drama,7.7,Suresh Sangaiah,Suresh Sangaiah,276,2017,9,8,8.233333333\nOru Iyakkunarin Kadhal Diary,Drama,6.4,V Brabhakar,Velu Prabhakaran,15560,2017,8,9,7.8\n7 Naatkal,Thriller,4.4,Gautham V.R.,M.S. Bhaskar,14763,2017,7,9,6.8\nThondan,Crime,6,Samuthirakani,Arthana Binu,242,2017,4,8,6\nBrindavanam,Drama,6.8,Radha Mohan,Arulnithi,1061,2017,8,8,7.6\nInayathalam,Drama,2.9,Sankar Suresh,Shankar-Suresh,59340,2017,5,9,5.633333333\nSangili Bungili Kadhava Thorae,Comedy,5.3,Ike Radha,Nivas Adithan,3026,2017,6,8,6.433333333\nYeidhavan,Action,6,Sakthi Rajasekaran,Sandra Amy,71417,2017,3,9,6\nSaravanan Irukka Bayamaen,Action,2.9,Ezhil,Karai Natrajan,159,2017,2,8,4.3\nEnga Amma Rani,Action,6.1,S. Bani,Dhansika,47566,2017,1,9,5.366666667\nBaahubali 2: The Conclusion,Action,8.2,S.S. Rajamouli,Prabhas,71418,2017,4,8,6.733333333\nNagarvalam,Drama,5.8,Marxx,Yogi Babu,35314,2017,7,9,7.266666667\nSathya,Action,2.7,Deepan,Roma Asrani,110,2017,8,8,6.233333333\nKadamban - Taqatwar,Action,5.4,N. Ragavan,Arya,363,2017,5,9,6.466666667\nSivalinga - Kanchana Returns,Horror,4.7,P. Vasu,Bhanupriya,361,2017,6,7,5.9\nPower Paandi,Action,7.6,Dhanush,Dhanush,1179,2017,9,7,7.866666667\n8 Thottakkal,Action,7.6,Sri Ganesh,Vetri,1394,2017,4,8,6.533333333\nKaatru Veliyidai,Romance,5.9,Mani Ratnam,Karthi,1669,2017,7,9,7.3\nDora,Action,5.3,Dass Ramasamy,Nayanthara,701,2017,4,8,5.766666667\nKavan,Action,7.1,K.V. Anand,Vijay Sethupathi,1853,2017,5,9,7.033333333\nKadugu,Drama,7.5,Vijay Milton,Radhika Prasidhha,482,2017,4,8,6.5\nPaambhu Sattai,Action,6.2,Adam Dasan,Bobby Simha,125,2017,8,9,7.733333333\nDhayam,Thriller,4.6,Kannan Rangaswamy,Aira Agarval,32535,2017,5,8,5.866666667\nVaigai Express,Thriller,4.6,Shaji Kailas,Shaji Kailas,23,2017,6,7,5.866666667\nJulieum 4 Perum,Family,3.4,Satheesh,Amudhavaanan,7,2017,9,7,6.466666667\nBruce Lee,Action,2.4,Prashanth Pandiraj,Anandraj,146,2017,8,8,6.133333333\nKattappava Kanom,Comedy,5.1,Mani Seiyon,Yogi Babu,28454,2017,7,8,6.7\nOru Mugathirai,Drama,5.7,R. Senthil Nadan,Chaams,65651,2017,4,8,5.9\nMaanagaram,Action,8.1,Lokesh Kanagaraj,Sundeep Kishan,3350,2017,5,9,7.366666667\nACP Shiva,Action,3.3,Sai Ramani,Joy Badlani,352,2017,8,9,6.766666667\nMupparimanam,Romance,5.5,Adhiroopan,Aari,35706,2017,9,8,7.5\nYaakkai,Romance,5.6,Kuzhandai Velappan,M.S. Bhaskar,48519,2017,6,7,6.2\nPeranbu,Drama,9,Ram,Amudhavan Karuppiah,11506,2018,8,7,8\nMaari 2,Action,5.6,Balaji Mohan,Dhanush,1913,2018,7,8,6.866666667\nAdanga Maru,Action,7.1,Karthik Thangavel,Jayam Ravi,1696,2018,4,9,6.7\nKanaa,Drama,7.8,Arunraja Kamaraj,Aishwarya Rajesh,1225,2018,5,8,6.933333333\nSeethakaathi,Drama,7,Balaji Tharaneetharan,Vijay Sethupathi,714,2018,8,9,8\nThuppakki Munai,Action,6.3,Dinesh Selvaraj,Vikram Prabhu,370,2018,9,8,7.766666667\nThuppakki Munai,Action,6.3,Dinesh Selvaraj,Vikram Prabhu,370,2018,8,9,7.766666667\n2,Action,6.3,S. Shankar,Rajinikanth,20076,2018,7,8,7.1\nKaatrin Mozhi,Comedy,7.3,Radha Mohan,Jyotika,559,2018,8,9,8.1\nSarkar,Action,6.8,A.R. Murugadoss,Joseph Vijay,11994,2018,9,8,7.933333333\nPandem Kodi 2,Action,5.2,N. Linguswamy,Vishal,632,2018,5,9,6.4\nVada Chennai,Action,8.5,Vetrimaaran,Dhanush,8841,2018,8,8,8.166666667\nAan Devathai,Action,6.4,Thamira,Ilavarasu,120,2018,7,9,7.466666667\nRaatchasan,Action,8.7,Ram Kumar,Vishnu Vishal,17425,2018,8,8,8.233333333\nNota,Drama,6.4,Anand Shankar,Vijay Deverakonda,2306,2018,9,9,8.133333333\n96,Drama,8.6,C. Prem Kumar,Vijay Sethupathi,15523,2018,8,8,8.2\nPariyerum Perumal,Drama,8.8,Mari Selvaraj,Prabunath,6984,2018,7,9,8.266666667\nChekka Chivantha Vaanam,Action,7.3,Mani Ratnam,Slavisa Ivanovic,5118,2018,8,8,7.766666667\nRaja Ranguski,Mystery,6.6,Dharani Dharan,Shirish,262,2018,9,7,7.533333333\nSaamy Square,Action,4.5,Hari,Vikram,1090,2018,9,8,7.166666667\nU Turn,Mystery,7,Pawan Kumar,Samantha Ruth Prabhu,2292,2018,7,9,7.666666667\nSeema Raja,Action,4.5,Ponram,Sivakarthikeyan,1405,2018,5,8,5.833333333\nImaikkaa Nodigal,Action,7.4,R. Ajay Gnanamuthu,Nayanthara,4206,2018,8,7,7.466666667\nLakshmi,Drama,6.9,A.L. Vijay,Ditya Bhande,476,2018,5,8,6.633333333\nOdu Raja Odu,Comedy,7.1,Jathin Sanker Raj,Nishanth Ravindaran,86,2018,9,9,8.366666667\nKolamavu Kokila,Comedy,7.3,Nelson,Nayanthara,1976,2018,6,8,7.1\nPyaar Prema Kaadhal,Romance,6.6,Elan,Harish Kalyan,872,2018,5,7,6.2\nVishwaroopam 2,Action,5.9,Vishwaroopam,Kamal Haasan,2076,2018,4,8,5.966666667\nGhajinikanth,Comedy,5.3,Santhosh P. Jayakumar,Arya,437,2018,1,9,5.1\nJunga,Action,5.2,Gokul,Vijay Sethupathi,774,2018,2,8,5.066666667\nMohini,Horror,3.3,R. Madhesh,Trisha Krishnan,41485,2018,3,7,4.433333333\nChinababu,Action,7,Pandiraj,Karthi,1896,2018,6,8,7\nTamizh Padam 2.0,Comedy,6.5,C.S. Amudhan,Jiiva,1286,2018,9,9,8.166666667\nGoli Soda 2,Drama,7.3,Vijay Milton,Samuthirakani,642,2018,8,8,7.766666667\nIravukku Aayiram Kangal,Action,7.3,Mu. Maran,Abhinayashree,978,2018,7,9,7.766666667\nIrumbu Thirai,Action,7.7,P.S. Mithran,Vishal,3373,2018,8,8,7.9\nMahanati,Biography,8.5,Savitri,Nag Ashwin,8703,2018,5,9,7.5\nIruttu Araiyil Murattu Kuthu,Horror,4.2,Santhosh P. Jayakumar,Yaashika Aanand,700,2018,6,9,6.4\nKaala,Action,6.7,Pa. Ranjith,Rajinikanth,7486,2018,5,8,6.566666667\nKaru,Drama,5.7,A.L. Vijay,Sai Pallavi,416,2018,4,8,5.9\nMercury,Horror,6.1,Karthik Subbaraj,Prabhu Deva,827,2018,5,8,6.366666667\nTik Tik Tik,Action,6.1,Shakti Soundar Rajan,Jayam Ravi,2172,2018,8,7,7.033333333\n6 Athiyayam,Horror,4.2,Ajayan Bala,Lokesh Rajendran,32,2018,8,8,6.733333333\nNaachiyaar,Action,6.8,Bala,Ivana,6140,2018,5,7,6.266666667\nSavarakathi,Comedy,7.1,G.R. Adithya,Ram,420,2018,5,8,6.7\nKalakalappu 2,Comedy,4.9,Sundar C.,Yogi Babu,572,2018,7,9,6.966666667\nMerku Thodarchi Malai,Drama,8.6,Lenin Bharati,Leninbharati,35981,2018,8,8,8.2\nBhaagamathie,Action,7,Ashok G.,Anushka Shetty,2209,2018,9,9,8.333333333\nNimir,Comedy,6.3,Priya Darshan,Priyadarshan,55126,2018,8,7,7.1\nOru Nalla Naal Paathu Solren,Comedy,6.8,P. Arumugakumar,Annayya,1877,2018,7,8,7.266666667\nThaanaa Serndha Koottam,Action,6.8,Vignesh Shivan,Suriya,4655,2018,5,9,6.933333333\nSketch,Action,5.7,Vijay Chandar,Vikram,1589,2018,7,9,7.233333333\nEnai Noki Paayum Thota,Action,5.7,Gautham Vasudev Menon,Dhanush,1198,2019,8,8,7.233333333\nAdithya Varma,Drama,6.4,Gireesaaya,Dhruv Vikram,596,2019,8,7,7.133333333\nKaithi,Action,8.5,Lokesh Kanagaraj,Karthi,7603,2019,9,8,8.5\nBigil,Action,6.8,Atlee Kumar,Joseph Vijay,9299,2019,9,9,8.266666667\n100% Kadhal,Comedy,4.6,M.M. Chandramouli,G.V.

In [12]:
with open(r"C:\Users\gnana\Downloads\Tamil_movies_dataset.csv","r")as file:
    k=file.readlines()
    for i in k:
        print(i)

MovieName,Genre,Rating,Director,Actor,PeopleVote,Year,Hero_Rating,movie_rating,content_rating

Mouna Guru,Action,7.7,Santha Kumar,Arulnithi,746,2011,8,8,7.9

7 Aum Arivu,Action,6.2,A.R. Murugadoss,Suriya,9479,2011,9,9,8.066666667

Vaagai Sooda Vaa,Comedy,8,A. Sarkunam,Vimal,14522,2011,8,7,7.666666667

Mankatha,Action,7.6,Venkat Prabhu,Ajith Kumar,12276,2011,6,8,7.2

Kanchana: Muni 2,Comedy,6.5,Lawrence Raghavendra,Lawrence Raghavendra,1044,2011,8,9,7.833333333

Deiva Thirumagal,Drama,8.1,A.L. Vijay,Vikram,44517,2011,9,9,8.7

Vaanam,Action,7.2,Radha Krishna Jagarlamudi,T.R. Silambarasan,1307,2011,7,8,7.4

Ko,Action,7.8,K.V. Anand,Jiiva,4759,2011,9,7,7.933333333

Payanam,Action,7.3,Radha Mohan,Nagarjuna Akkineni,677,2011,6,8,7.1

Yutham Sei,Crime,8,Myshkin,Cheran,1678,2011,4,9,7

Aadukalam,Action,8.1,Vetrimaaran,Dhanush,4456,2011,8,9,8.366666667

Naduvula Konjam Pakkatha Kaanom,Comedy,8.2,Balaji Tharaneetharan,Vijay Sethupathi,4530,2012,7,8,7.733333333

Thuppakki,Action,7.9,A.R. Murugadoss,Joseph Vijay,22577,2012,9,9,8.633333333

Pizza,Horror,8,Karthik Subbaraj,Vijay Sethupathi,6528,2012,2,8,6

Naan,Crime,7.5,Jeeva Shankar,Vijay Antony,1365,2012,3,7,5.833333333

The Fly,Action,7.7,S.S. Rajamouli,J.V.V. Sathyanarayana,20590,2012,5,7,6.566666667

Kalakalappu,Comedy,6.9,Sundar C.,Vimal,1019,2012,7,8,7.3

Vazhakku Enn 18/9,Crime,8.3,Balaji Sakthivel,Sri,1915,2012,5,9,7.433333333

Kumki,Drama,7,Prabu Solomon,Vikram Prabhu,1231,2012,8,9,8

Neethaane En Ponvasantham,Romance,6.5,Gautham Vasudev Menon,Jiiva,1500,2012,9,8,7.833333333

Thalaimuraigal,Drama,7.6,Balu Mahendra,Karthick,40034,2013,8,7,7.533333333

Biriyani,Action,5.7,Venkat Prabhu,Karthi,1272,2013,7,8,6.9

Ivan Veramaathiri,Action,6,M. Saravanan,Vikram Prabhu,290,2013,4,9,6.333333333

Kalyana Samayal Saadham,Comedy,7.1,R.S. Prasanna,Prasanna,117,2013,5,8,6.7

Irandam Ulagam,Action,5.7,K. Selvaraghavan,Arya,1101,2013,8,8,7.233333333

Pandiya Naadu,Action,7.2,Suseenthiran,Vishal,1168,2013,9,8,8.066666667

Arrambam,Action,7,Vishnuvardhan,Ajith Kumar,8415,2013,6,9,7.333333333

Onaayum Aattukkuttiyum,Action,8.2,Myshkin,Myshkin,2181,2013,8,8,8.066666667

Raja Rani,Comedy,7.6,Atlee Kumar,Arya,4088,2013,9,9,8.533333333

6 Candles,Thriller,7,V.Z. Dhorai,Sandra Amy,16247,2013,4,9,6.666666667

Moodar Koodam,Comedy,7.7,Naveen,Naveen,1081,2013,5,8,6.9

Varuthapadatha Valibar Sangam,Comedy,6.7,Ponram,Sivakarthikeyan,1352,2013,6,8,6.9

Thanga Meengal,Drama,7.9,Ram,Ram,791,2013,4,9,6.966666667

Aadhalal Kadhal Seiveer,Romance,7.2,Suseenthiran,Santhosh Ramesh,62323,2013,5,8,6.733333333

Maryan,Adventure,7.1,Ganapathy Bharat,Dhanush,2761,2013,6,9,7.366666667

Singam 2,Action,6.3,Hari,Suriya,5369,2013,8,9,7.766666667

Theeya Velai Seiyyanum Kumaru,Comedy,6.1,Sundar C.,Siddharth,1320,2013,7,8,7.033333333

Neram,Action,7.5,Alphonse Puthren,Nivin Pauly,4292,2013,5,8,6.833333333

Soodhu Kavvum,Comedy,8.3,Nalan Kumarasamy,Vijay Sethupathi,8307,2013,6,9,7.766666667

Ethir Neechal,Comedy,6.8,R.S. Durai Senthilkumar,Sivakarthikeyan,1747,2013,8,9,7.933333333

Kedi Billa Killadi Ranga,Comedy,5.5,Pandiraj,Vimal,578,2013,7,7,6.5

Paradesi,Drama,8,Bala,Atharvaa Murali,1644,2013,8,8,8

Kaakkaa Muttai,Comedy,8.4,M. Manikandan,Ramesh,5011,2014,9,7,8.133333333

Kayal,Romance,6.4,Prabu Solomon,Chandran,320,2014,8,8,7.466666667

Pisasu,Horror,7.6,Myshkin,Naga,1658,2014,7,9,7.866666667

Lingaa,Action,5.6,K.S. Ravikumar,Rajinikanth,4807,2014,4,8,5.866666667

Kaaviya Thalaivan,Drama,7.6,Vasanthabalan,Siddharth,1133,2014,5,7,6.533333333

Kaththi,Action,7.9,A.R. Murugadoss,Joseph Vijay,16760,2014,8,7,7.633333333

Jeeva,Drama,7.5,Suseenthiran,Vishnu Vishal,944,2014,9,9,8.5

Madras,Action,8,Pa. Ranjith,Karthi,3102,2014,8,8,8

Kathai Thiraikathai Vasanam Iyakkam,Drama,6.8,Parthiban,Thambi Ramaiah,586,2014,7,7,6.933333333

Jigarthanda,Action,8.3,Karthik Subbaraj,Siddharth,9578,2014,8,7,7.766666667

Velaiilla Pattadhari,Action,7.8,Velraj,Dhanush,5039,2014,9,8,8.266666667

Sathuranga Vettai,Crime,8.1,H. Vinoth,Nataraja Subramanian,2409,2014,8,9,8.366666667

Saivam,Drama,6.8,A.L. Vijay,Nassar,59767,2014,7,9,7.6

Mundaasupatti,Comedy,7.6,Ram Kumar,Vishnu Vishal,1118,2014,4,8,6.533333333

Kochadaiiyaan,Animation,6.3,Soundarya R. Ashwin,Rajinikanth,4692,2014,5,8,6.433333333

Vaayai Moodi Pesavum,Comedy,6.7,Balaji Mohan,Dulquer Salmaan,1448,2014,9,9,8.233333333

Cuckoo,Drama,7.8,Raju Murugan,Dinesh,617,2014,8,7,7.6

Thegidi,Crime,7.8,P. Ramesh,Ashok Selvan,27868,2014,7,8,7.6

Pannaiyarum Padminiyum,Comedy,7.8,S.U. Arun Kumar,Vijay Sethupathi,1375,2014,5,9,7.266666667

Goli Soda,Action,7.7,Vijay Milton,Kishore Kumar G.,905,2014,8,7,7.566666667

Veeram,Action,6.5,Siva,Ajith Kumar,6655,2014,9,7,7.5

Rajini Murugan,Action,5.7,Ponram,Sivakarthikeyan,1322,2015,6,8,6.566666667

Visaaranai,Crime,8.5,Vetrimaaran,Dinesh,6219,2015,8,9,8.5

Pasanga 2,Drama,7.5,Pandiraj,Suriya,1031,2015,7,7,7.166666667

Thoongaavanam,Action,7,Rajesh M. Selva,Kamal Haasan,1819,2015,5,8,6.666666667

Naanum Rowdy Thaan,Action,7.3,Vignesh Shivan,Vijay Sethupathi,3354,2015,8,9,8.1

Kuttram Kadithal,Drama,8,Bramma G.,Master Ajay,665,2015,4,8,6.666666667

Kirumi,Crime,7,Anu Charan,Anucharan,45686,2015,7,7,7

Maya,Horror,7.6,Ashwin Saravanan,Nayanthara,1302,2015,9,8,8.2

Thani Oruvan,Action,8.4,Mohan Raja,Jayam Ravi,15421,2015,6,8,7.466666667

Papanasam,Drama,8.4,Jeethu Joseph,Kamal Haasan,5295,2015,8,7,7.8

Indru Netru Naalai,Comedy,8,R. Ravikumar,Vishnu Vishal,3339,2015,5,9,7.333333333

Demonte Colony,Horror,6.9,R. Ajay Gnanamuthu,Arulnithi,1725,2015,8,9,7.966666667

36 Vayadhinile,Drama,7.1,Roshan Andrews,Jyotika,647,2015,5,8,6.7

Uttama Villain,Comedy,7.2,Ramesh Aravind,Kamal Haasan,2561,2015,7,7,7.066666667

Kanchana 2,Comedy,5.5,Lawrence Raghavendra,Lawrence Raghavendra,1261,2015,8,8,7.166666667

OK Kanmani,Romance,7.4,Mani Ratnam,Dulquer Salmaan,4611,2015,6,9,7.466666667

Rajathandhiram,Action,7.7,A.G. Amid,Veera Bahu,1154,2015,3,8,6.233333333

Enakkul Oruvan,Thriller,7.7,Prasad Ramar,Siddharth,1456,2015,2,7,5.566666667

Press 1 for Tamil,Comedy,7,Ramprakash Rayappa,Nakhul,850,2015,4,8,6.333333333

Yennai Arindhaal,Action,7.3,Gautham Vasudev Menon,Ajith Kumar,7740,2015,7,9,7.766666667

I,Action,7.3,S. Shankar,Vikram,18345,2015,8,9,8.1

Dhuruvangal Pathinaaru,Action,8.4,Karthick Naren,Rahman,10895,2016,5,8,7.133333333

Chennai 600028 Second Innings,Comedy,7,Venkat Prabhu,Jai,937,2016,1,7,5

Achcham Yenbadhu Madamaiyada,Action,6.4,Gautham Vasudev Menon,T.R. Silambarasan,1896,2016,6,7,6.466666667

Ammani,Drama,7.9,Lakshmi Ramakrishnan,Semmalar Annam,52730,2016,9,7,7.966666667

Aandavan Kattalai,Drama,8.1,M. Manikandan,Vijay Sethupathi,2060,2016,8,8,8.033333333

Kuttrame Thandanai,Crime,7.8,M. Manikandan,Vidharth,60939,2016,7,7,7.266666667

Dharmadurai,Drama,7.5,Seenu Ramasamy,Vijay Sethupathi,1568,2016,8,9,8.166666667

Joker,Comedy,8.4,Raju Murugan,Raju Saravanan,2830,2016,5,9,7.466666667

Kabali,Action,6.2,Pa. Ranjith,Rajinikanth,11149,2016,8,8,7.4

Metro,Action,7.3,Ananda Krishnan,Shirish,697,2016,5,9,7.1

Iraivi,Crime,8,Karthik Subbaraj,S.J. Suryah,2736,2016,9,8,8.333333333

Uriyadi,Action,8.1,Vijay Kumar,Vijay Kumar,1878,2016,8,7,7.7

24,Action,7.8,Vikram K. Kumar,Suriya,15774,2016,7,8,7.6

Theri,Action,7.1,Atlee Kumar,Joseph Vijay,12365,2016,8,9,8.033333333

Oopiri,Comedy,8,Vamshi Paidipally,Nagarjuna Akkineni,3915,2016,9,9,8.666666667

Kadhalum Kadanthu Pogum,Comedy,7.3,Nalan Kumarasamy,Vijay Sethupathi,2407,2016,8,8,7.766666667

Pichaikkaran,Action,7.6,Sasi,Vijay Antony,1437,2016,7,9,7.866666667

Saala Khadoos,Action,7.6,Sudha Kongara,Madhavan,10941,2016,8,8,7.866666667

Crime 23,Action,7.4,Arivazhagan Venkatachalam,Arun Vijay,1915,2017,4,9,6.8

Muthuramalingam,Action,1.6,Rajadurai,Priya Anand,14063,2017,5,9,5.2

Dream Factory,Drama,6.7,Arun Chidambaram,Jiya Anil Manne,124,2017,6,8,6.9

Yaman,Action,6.2,Jeeva Shankar,Vijay Antony,454,2017,9,8,7.733333333

Ennodu Vilayadu,Thriller,5.6,Arun Krishnaswami,Bharath Srinivasan,77,2017,8,7,6.866666667

Kadhal Kan Kattudhe,Drama,6.5,Shivaraj,Aneeruth,30623,2017,7,8,7.166666667

Pagadi Aattam,Crime,5.8,Ram K. Chandran,Rahman,79,2017,4,9,6.266666667

Rum,Horror,4.2,Sai Bharath,Arjun Chidambaram,118,2017,5,9,6.066666667

Singam 3,Action,6.3,Hari,Suriya,5063,2017,8,8,7.433333333

Bogan,Action,6.4,Lakshman,Jayam Ravi,1358,2017,9,8,7.8

Enakku Vaaitha Adimaigal,Comedy,5.8,Mahendran Rajamani,Jai,399,2017,8,7,6.933333333

Koditta Idangalai Nirappuga,Comedy,6.4,Parthiban,Shanthnu Bhagyaraj,65921,2017,7,8,7.133333333

Adhe Kangal,Action,7.3,Rohin Venkatesan,R. Aravindraj,961,2017,4,9,6.766666667

Bairavaa,Action,5.9,Bharathan,Joseph Vijay,7376,2017,5,9,6.633333333

Lens,Drama,6.9,Jayaprakash Radhakrishnan,Anand Sami,942,2017,8,8,7.633333333

Aruvi,Drama,8.6,Arun Prabhu Purushothaman,Aditi Balan,9890,2017,7,7,7.533333333

Ulkuththu,Thriller,6.7,Caarthick Raju,Dr. Chef Damodaran,17655,2017,9,8,7.9

Balloon,Horror,4.6,Sinish,Anjali,274,2017,5,9,6.2

Kalavaadiya Pozhuthugal,Romance,6.1,Thangar Bachan,Bhoomika Chawla,48,2017,8,8,7.366666667

Velaikkaran,Action,7.3,Mohan Raja,Sivakarthikeyan,2984,2017,6,7,6.766666667

Sakka Podu Podu Raja,Action,4.2,G.L. Sethuraman,Aryan,357,2017,9,8,7.066666667

Bhrama.com,Action,5.1,P.S. Vijayakumar,Bhagyaraj,64,2017,7,9,7.033333333

Chennai 2 Singapore,Comedy,6.1,Abbas Akbaar,Abbas Akbar,137,2017,8,8,7.366666667

12-12-1950,Comedy,5.4,Selvaah,Yogi Babu,69977,2017,8,7,6.8

Kodiveeran,Action,4.8,M. Muthaiya,Gnanasambandam,117,2017,9,8,7.266666667

Richie,Action,5.3,Gautham Ramachandran,Nivin Pauly,706,2017,9,9,7.766666667

Annadurai,Action,5.3,G. Srinivasan,Vijay Antony,213,2017,7,8,6.766666667

Thiruttu Payale 2,Thriller,6.7,Susi Ganesan,Bobby Simha,658,2017,8,9,7.9

English Padam,Comedy,1.2,Kumaresh Kumar,Sreeja Das,24,2017,4,8,4.4

Indrajith,Action,3.3,Kalaprabhu Thanu,Gautham Karthik,150,2017,5,8,5.433333333

En Aaloda Seruppa Kaanom,Comedy,5,Jagan,K.P. Jagan,61,2017,8,9,7.333333333

Theeran Adhigaram Ondru,Action,8.2,H. Vinoth,Karthi,8685,2017,4,8,6.733333333

C/o Surya,Action,5.6,Suseenthiran,Sundeep Kishan,175,2017,7,9,7.2

Ippadai Vellum,Action,5.7,Gaurav Narayanan,Udhayanidhi Stalin,272,2017,8,8,7.233333333

Aramm,Drama,7.8,Gopi Nainar,Nayanthara,1411,2017,5,7,6.6

The House Next Door,Horror,6.8,Milind Rau,Prakash Belawadi,1854,2017,8,7,7.266666667

Vizhithiru,Drama,5.9,Meera Kathiravan,Abhinaya,103,2017,9,8,7.633333333

Kadaisi Bench Karthi,Comedy,4.1,Ravee Paargavan,Gnanasambandam,36,2017,8,9,7.033333333

Mersal,Action,7.7,Atlee Kumar,Joseph Vijay,23383,2017,8,8,7.9

Meyaadha Maan,Romance,7.2,Rathna Kumar,Vaibhav Reddy,870,2017,8,7,7.4

Solo,Action,7.1,Bejoy Nambiar,Dulquer Salmaan,2772,2017,4,8,6.366666667

Hara Hara Mahadevaki,Comedy,5.3,Santhosh P. Jayakumar,Kovai Babu,450,2017,7,9,7.1

Karuppan,Action,5.6,R. Panneerselvam,Sami Rajalingam,520,2017,5,8,6.2

Spyder,Action,6.6,A.R. Murugadoss,Mahesh Babu,8652,2017,7,7,6.866666667

Bayama Irukku,Comedy,5.3,Jawahar,Santhosh Prathap,70,2017,3,8,5.433333333

Aayirathil Iruvar,Action,4.6,Saran,Vinay Rai,57587,2017,5,9,6.2

Kalavu Thozhirchalai,Thriller,5.9,T Krishna Samy,T. Krishnasamy,25,2017,6,8,6.633333333

Veedevadu,Thriller,5.5,Tatineni Satya,Esha Gupta,44,2017,2,7,4.833333333

Thupparivaalan,Action,7.5,Myshkin,Vishal,3405,2017,8,8,7.833333333

Kathanayagan,Comedy,4.2,Tha. Muruganatham,Meera Krishna,30228,2017,7,9,6.733333333

Neruppu Da,Action,4.3,Nikki Galrani,Nagineedu,10330,2017,8,9,7.1

Kurangu Bommai,Drama,8.1,Nithilan,Vidharth,1093,2017,7,8,7.7

Maayavan,Action,7.3,C.V. Kumar,Sundeep Kishan,1468,2017,2,9,6.1

Puriyaatha Puthir,Thriller,6.6,Ranjit Jeyakodi,Vijay Sethupathi,771,2017,8,9,7.866666667

Vivegam,Action,5.6,Siva,Ajith Kumar,10389,2017,9,8,7.533333333

Thappu Thanda,Crime,6,Srikantan,Ajay Ghosh,42,2017,7,8,7

Taramani,Drama,7.5,Ram,Anjali,1252,2017,4,7,6.166666667

Velaiyilla Pattathari 2,Action,5.4,Soundarya R. Ashwin,Riaz Ahmed,1783,2017,8,8,7.133333333

Podhuvaga En Manasu Thangam,Comedy,3.8,Thalapathy Prabhu,Parthiban,115,2017,5,9,5.933333333

Kootathil Oruthan,Comedy,6.7,T.J. Gnanavel,Ashok Selvan,363,2017,7,8,7.233333333

Nibunan,Action,6.6,Arun Vaidyanathan,Varalaxmi Sarathkumar,782,2017,4,9,6.533333333

Meesaya murukku,Biography,7.6,Hiphop Tamizha Adhi,Hiphop Tamizha Adhi,1869,2017,8,9,8.2

Vikram Vedha,Action,8.7,Gayatri,Pushkar,23249,2017,9,8,8.566666667

Rubaai,Action,6.1,M. Anbazhagan,Anandhi,41952,2017,8,7,7.033333333

Magalir Mattum,Drama,6.3,Bramma G.,Jyotika,455,2017,9,7,7.433333333

Pandigai,Action,6.5,Feroz,Kreshna,245,2017,7,8,7.166666667

Thiri,Drama,5.2,Ashok Amritharaj S.,A.L. Azhagappan,33926,2017,8,9,7.4

Gemini Ganesanum Suruli Rajanum,Comedy,5.8,Ilavarasu Odam,Regina Cassandra,387,2017,9,9,7.933333333

Chennaiyil Oru Naal 2,Thriller,4.6,Jpr,Sarath Kumar,84,2017,7,8,6.533333333

Ivan Thanthiran,Action,6.3,R. Kannan,RJ Balaji,28334,2017,8,7,7.1

Adhagappattathu Magajanangalay,Comedy,5,Inba Sekhar,Inbasekhar,19592,2017,9,7,7

Yaanum Theeyavan,Action,6.1,Prashanth G Sekr,Prashanth G Sekar,26862,2017,8,8,7.366666667

Vanamagan,Action,5.5,A.L. Vijay,Arjun,599,2017,7,9,7.166666667

Anbanavan Asaradhavan Adangadhavan,Action,2.3,Adhik Ravichandran,Tamannaah Bhatia,510,2017,5,9,5.433333333

Maragatha Nananya,Adventure,7,Ark Saravan,Aadhi,1144,2017,8,7,7.333333333

Uru,Thriller,5.9,Vicky Anand,Vicky Anand,275,2017,8,8,7.3

Peechaankai,Comedy,6.5,Ashok,Rskarthiik,53,2017,3,8,5.833333333

Rangoon,Action,7.1,Rajkumar Periasamy,Gautham Karthik,560,2017,8,7,7.366666667

Sathriyan,Action,4.8,Vikram Prabhu,Manjima Mohan,51758,2017,7,8,6.6

Bongu,Crime,5.3,Taj,Pooja Bisht,93,2017,8,7,6.766666667

Oru Kidayin Karunai Manu,Drama,7.7,Suresh Sangaiah,Suresh Sangaiah,276,2017,9,8,8.233333333

Oru Iyakkunarin Kadhal Diary,Drama,6.4,V Brabhakar,Velu Prabhakaran,15560,2017,8,9,7.8

7 Naatkal,Thriller,4.4,Gautham V.R.,M.S. Bhaskar,14763,2017,7,9,6.8

Thondan,Crime,6,Samuthirakani,Arthana Binu,242,2017,4,8,6

Brindavanam,Drama,6.8,Radha Mohan,Arulnithi,1061,2017,8,8,7.6

Inayathalam,Drama,2.9,Sankar Suresh,Shankar-Suresh,59340,2017,5,9,5.633333333

Sangili Bungili Kadhava Thorae,Comedy,5.3,Ike Radha,Nivas Adithan,3026,2017,6,8,6.433333333

Yeidhavan,Action,6,Sakthi Rajasekaran,Sandra Amy,71417,2017,3,9,6

Saravanan Irukka Bayamaen,Action,2.9,Ezhil,Karai Natrajan,159,2017,2,8,4.3

Enga Amma Rani,Action,6.1,S. Bani,Dhansika,47566,2017,1,9,5.366666667

Baahubali 2: The Conclusion,Action,8.2,S.S. Rajamouli,Prabhas,71418,2017,4,8,6.733333333

Nagarvalam,Drama,5.8,Marxx,Yogi Babu,35314,2017,7,9,7.266666667

Sathya,Action,2.7,Deepan,Roma Asrani,110,2017,8,8,6.233333333

Kadamban - Taqatwar,Action,5.4,N. Ragavan,Arya,363,2017,5,9,6.466666667

Sivalinga - Kanchana Returns,Horror,4.7,P. Vasu,Bhanupriya,361,2017,6,7,5.9

Power Paandi,Action,7.6,Dhanush,Dhanush,1179,2017,9,7,7.866666667

8 Thottakkal,Action,7.6,Sri Ganesh,Vetri,1394,2017,4,8,6.533333333

Kaatru Veliyidai,Romance,5.9,Mani Ratnam,Karthi,1669,2017,7,9,7.3

Dora,Action,5.3,Dass Ramasamy,Nayanthara,701,2017,4,8,5.766666667

Kavan,Action,7.1,K.V. Anand,Vijay Sethupathi,1853,2017,5,9,7.033333333

Kadugu,Drama,7.5,Vijay Milton,Radhika Prasidhha,482,2017,4,8,6.5

Paambhu Sattai,Action,6.2,Adam Dasan,Bobby Simha,125,2017,8,9,7.733333333

Dhayam,Thriller,4.6,Kannan Rangaswamy,Aira Agarval,32535,2017,5,8,5.866666667

Vaigai Express,Thriller,4.6,Shaji Kailas,Shaji Kailas,23,2017,6,7,5.866666667

Julieum 4 Perum,Family,3.4,Satheesh,Amudhavaanan,7,2017,9,7,6.466666667

Bruce Lee,Action,2.4,Prashanth Pandiraj,Anandraj,146,2017,8,8,6.133333333

Kattappava Kanom,Comedy,5.1,Mani Seiyon,Yogi Babu,28454,2017,7,8,6.7

Oru Mugathirai,Drama,5.7,R. Senthil Nadan,Chaams,65651,2017,4,8,5.9

Maanagaram,Action,8.1,Lokesh Kanagaraj,Sundeep Kishan,3350,2017,5,9,7.366666667

ACP Shiva,Action,3.3,Sai Ramani,Joy Badlani,352,2017,8,9,6.766666667

Mupparimanam,Romance,5.5,Adhiroopan,Aari,35706,2017,9,8,7.5

Yaakkai,Romance,5.6,Kuzhandai Velappan,M.S. Bhaskar,48519,2017,6,7,6.2

Peranbu,Drama,9,Ram,Amudhavan Karuppiah,11506,2018,8,7,8

Maari 2,Action,5.6,Balaji Mohan,Dhanush,1913,2018,7,8,6.866666667

Adanga Maru,Action,7.1,Karthik Thangavel,Jayam Ravi,1696,2018,4,9,6.7

Kanaa,Drama,7.8,Arunraja Kamaraj,Aishwarya Rajesh,1225,2018,5,8,6.933333333

Seethakaathi,Drama,7,Balaji Tharaneetharan,Vijay Sethupathi,714,2018,8,9,8

Thuppakki Munai,Action,6.3,Dinesh Selvaraj,Vikram Prabhu,370,2018,9,8,7.766666667

Thuppakki Munai,Action,6.3,Dinesh Selvaraj,Vikram Prabhu,370,2018,8,9,7.766666667

2,Action,6.3,S. Shankar,Rajinikanth,20076,2018,7,8,7.1

Kaatrin Mozhi,Comedy,7.3,Radha Mohan,Jyotika,559,2018,8,9,8.1

Sarkar,Action,6.8,A.R. Murugadoss,Joseph Vijay,11994,2018,9,8,7.933333333

Pandem Kodi 2,Action,5.2,N. Linguswamy,Vishal,632,2018,5,9,6.4

Vada Chennai,Action,8.5,Vetrimaaran,Dhanush,8841,2018,8,8,8.166666667

Aan Devathai,Action,6.4,Thamira,Ilavarasu,120,2018,7,9,7.466666667

Raatchasan,Action,8.7,Ram Kumar,Vishnu Vishal,17425,2018,8,8,8.233333333

Nota,Drama,6.4,Anand Shankar,Vijay Deverakonda,2306,2018,9,9,8.133333333

96,Drama,8.6,C. Prem Kumar,Vijay Sethupathi,15523,2018,8,8,8.2

Pariyerum Perumal,Drama,8.8,Mari Selvaraj,Prabunath,6984,2018,7,9,8.266666667

Chekka Chivantha Vaanam,Action,7.3,Mani Ratnam,Slavisa Ivanovic,5118,2018,8,8,7.766666667

Raja Ranguski,Mystery,6.6,Dharani Dharan,Shirish,262,2018,9,7,7.533333333

Saamy Square,Action,4.5,Hari,Vikram,1090,2018,9,8,7.166666667

U Turn,Mystery,7,Pawan Kumar,Samantha Ruth Prabhu,2292,2018,7,9,7.666666667

Seema Raja,Action,4.5,Ponram,Sivakarthikeyan,1405,2018,5,8,5.833333333

Imaikkaa Nodigal,Action,7.4,R. Ajay Gnanamuthu,Nayanthara,4206,2018,8,7,7.466666667

Lakshmi,Drama,6.9,A.L. Vijay,Ditya Bhande,476,2018,5,8,6.633333333

Odu Raja Odu,Comedy,7.1,Jathin Sanker Raj,Nishanth Ravindaran,86,2018,9,9,8.366666667

Kolamavu Kokila,Comedy,7.3,Nelson,Nayanthara,1976,2018,6,8,7.1

Pyaar Prema Kaadhal,Romance,6.6,Elan,Harish Kalyan,872,2018,5,7,6.2

Vishwaroopam 2,Action,5.9,Vishwaroopam,Kamal Haasan,2076,2018,4,8,5.966666667

Ghajinikanth,Comedy,5.3,Santhosh P. Jayakumar,Arya,437,2018,1,9,5.1

Junga,Action,5.2,Gokul,Vijay Sethupathi,774,2018,2,8,5.066666667

Mohini,Horror,3.3,R. Madhesh,Trisha Krishnan,41485,2018,3,7,4.433333333

Chinababu,Action,7,Pandiraj,Karthi,1896,2018,6,8,7

Tamizh Padam 2.0,Comedy,6.5,C.S. Amudhan,Jiiva,1286,2018,9,9,8.166666667

Goli Soda 2,Drama,7.3,Vijay Milton,Samuthirakani,642,2018,8,8,7.766666667

Iravukku Aayiram Kangal,Action,7.3,Mu. Maran,Abhinayashree,978,2018,7,9,7.766666667

Irumbu Thirai,Action,7.7,P.S. Mithran,Vishal,3373,2018,8,8,7.9

Mahanati,Biography,8.5,Savitri,Nag Ashwin,8703,2018,5,9,7.5

Iruttu Araiyil Murattu Kuthu,Horror,4.2,Santhosh P. Jayakumar,Yaashika Aanand,700,2018,6,9,6.4

Kaala,Action,6.7,Pa. Ranjith,Rajinikanth,7486,2018,5,8,6.566666667

Karu,Drama,5.7,A.L. Vijay,Sai Pallavi,416,2018,4,8,5.9

Mercury,Horror,6.1,Karthik Subbaraj,Prabhu Deva,827,2018,5,8,6.366666667

Tik Tik Tik,Action,6.1,Shakti Soundar Rajan,Jayam Ravi,2172,2018,8,7,7.033333333

6 Athiyayam,Horror,4.2,Ajayan Bala,Lokesh Rajendran,32,2018,8,8,6.733333333

Naachiyaar,Action,6.8,Bala,Ivana,6140,2018,5,7,6.266666667

Savarakathi,Comedy,7.1,G.R. Adithya,Ram,420,2018,5,8,6.7

Kalakalappu 2,Comedy,4.9,Sundar C.,Yogi Babu,572,2018,7,9,6.966666667

Merku Thodarchi Malai,Drama,8.6,Lenin Bharati,Leninbharati,35981,2018,8,8,8.2

Bhaagamathie,Action,7,Ashok G.,Anushka Shetty,2209,2018,9,9,8.333333333

Nimir,Comedy,6.3,Priya Darshan,Priyadarshan,55126,2018,8,7,7.1

Oru Nalla Naal Paathu Solren,Comedy,6.8,P. Arumugakumar,Annayya,1877,2018,7,8,7.266666667

Thaanaa Serndha Koottam,Action,6.8,Vignesh Shivan,Suriya,4655,2018,5,9,6.933333333

Sketch,Action,5.7,Vijay Chandar,Vikram,1589,2018,7,9,7.233333333

Enai Noki Paayum Thota,Action,5.7,Gautham Vasudev Menon,Dhanush,1198,2019,8,8,7.233333333

Adithya Varma,Drama,6.4,Gireesaaya,Dhruv Vikram,596,2019,8,7,7.133333333

Kaithi,Action,8.5,Lokesh Kanagaraj,Karthi,7603,2019,9,8,8.5

Bigil,Action,6.8,Atlee Kumar,Joseph Vijay,9299,2019,9,9,8.266666667


In [23]:
import pandas as pd
df=pd.read_csv("Tamil_movies_dataset.csv")
df.tail()

,MovieName,Genre,Rating,Director,Actor,PeopleVote,Year,Hero_Rating,movie_rating,content_rating
324,Dhilluku Dhuddu 2,Comedy,5.3,Rambala,Santhanam,497,2019,7,9,7.100000
325,Dev,Action,4.8,Rajath Ravishankar,Karthi,724,2019,5,8,5.933333
326,Charlie Chaplin 2,Comedy,3.8,Sakthi Chidambaram,Prabhu Deva,215,2019,4,7,4.933333
327,Petta,Action,7.3,Karthik Subbaraj,Rajinikanth,7545,2019,8,8,7.766667
328,Viswasam,Action,6.7,Siva,Ajith Kumar,5907,2019,8,9,7.900000

In [24]:
import pandas as pd
df=pd.read_csv("Tamil_movies_dataset.csv")
df.head()

,MovieName,Genre,Rating,Director,Actor,PeopleVote,Year,Hero_Rating,movie_rating,content_rating
0,Mouna Guru,Action,7.7,Santha Kumar,Arulnithi,746,2011,8,8,7.900000
1,7 Aum Arivu,Action,6.2,A.R. Murugadoss,Suriya,9479,2011,9,9,8.066667
2,Vaagai Sooda Vaa,Comedy,8.0,A. Sarkunam,Vimal,14522,2011,8,7,7.666667
3,Mankatha,Action,7.6,Venkat Prabhu,Ajith Kumar,12276,2011,6,8,7.200000
4,Kanchana: Muni 2,Comedy,6.5,Lawrence Raghavendra,Lawrence Raghavendra,1044,2011,8,9,7.833333

In [25]:
import pandas as pd
df=pd.read_csv("Tamil_movies_dataset.csv")
df

,MovieName,Genre,Rating,Director,Actor,PeopleVote,Year,Hero_Rating,movie_rating,content_rating
0,Mouna Guru,Action,7.7,Santha Kumar,Arulnithi,746,2011,8,8,7.900000
1,7 Aum Arivu,Action,6.2,A.R. Murugadoss,Suriya,9479,2011,9,9,8.066667
2,Vaagai Sooda Vaa,Comedy,8.0,A. Sarkunam,Vimal,14522,2011,8,7,7.666667
3,Mankatha,Action,7.6,Venkat Prabhu,Ajith Kumar,12276,2011,6,8,7.200000
4,Kanchana: Muni 2,Comedy,6.5,Lawrence Raghavendra,Lawrence Raghavendra,1044,2011,8,9,7.833333
...,...,...,...,...,...,...,...,...,...,...
324,Dhilluku Dhuddu 2,Comedy,5.3,Rambala,Santhanam,497,2019,7,9,7.100000
325,Dev,Action,4.8,Rajath Ravishankar,Karthi,724,2019,5,8,5.933333
326,Charlie Chaplin 2,Comedy,3.8,Sakthi Chidambaram,Prabhu Deva,215,2019,4,7,4.933333
327,Petta,Action,7.3,Karthik Subbaraj,Rajinikanth,7545,2019,8,8,7.766667
328,Viswasam,Action,6.7,Siva,Ajith Kumar,5907,2019,8,9,7.900000

In [5]:
with open(r"C:\Users\gnana\Downloads\ipl2024 Matches.csv","r")as file:
    k=file.readlines()
    for i in k:
        print(i)

id,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts

1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman

2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav

3,"March 23,2024",Kolkata,Hyderabad,Hyderabad,Field,208,7,204,7,Kolkata,Andre Russell,Andre Russell,T Natarajan

4,"March 24,2024",Rajasthan,Lucknow,Rajasthan,Bat,193,4,173,6,Rajasthan,Sanju Samson,Sanju Samson,Trent Boult

5,"March 24,2024",Gujarat,Mumbai,Mumbai,Field,168,6,162,9,Gujarat,Sai Sudharsan,Dewald Brevis,Jasprit Bumrah

6,"March 25,2024",Punjab,Banglore,Banglore,Field,176,6,178,6,Banglore,Virat Kohli,Virat Kohli,Harpreet Brar

7,"March 26,2024",Chennai,Gujarat,Gujarat,Field,206,6,143,8,Chennai,Shivam Dube,Shivam Dube,Tushar Deshpande

8,"March 27,2024",Hyderabad,Mumbai,Mumbai,Field,277,3,246,5,Hyderabad,Abhishek Sharma,Heinrich Klaasen,Pat Cummins

9,"March 28,2024",Rajasthan,Delhi,Delhi,Field,185,5,173,5,Rajasthan,Riyan Parag,Riyan Parag,Yuzvendra Chahal

10,"March 29,2024",Banglore,Kolkata,Kolkata,Field,182,6,186,3,Kolkata,Sunil Narine,Virat Kohli ,Andre Russell

11,"March 30,2024",Lucknow,Punjab,Lucknow,Bat,199,8,178,5,Lucknow,Mayank Yadav,Shikhar Dhawan,Mayank Yadav

12,"March 31,2024",Hyderabad,Gujarat,Hyderabad,Bat,162,8,168,3,Gujarat,Mohit Sharma,Sai Sudharsan,Mohit Sharma

13,"March 31,2024",Delhi,Chennai,Delhi,Bat,191,5,171,6,Delhi,Khaleel Ahmed,Jos Buttler,Mukesh Kumar

14,"April 1,2024",Mumbai,Rajasthan,Rajasthan,Field,125,9,127,4,Rajasthan,Trent Boult,Riyan Parag ,Yuzvendra Chahal

15,"April 2,2024",Lucknow,Banglore,Banglore,Field,181,5,153,10,Lucknow,Mayank Yadav,Quinton de Kock,Mayank Yadav

16,"April 3,2024",Kolkata,Delhi,Kolkata,Bat,272,7,166,10,Kolkata,Sunil Narine,Sunil Narine,Vaibhav Arora

17,"April 4,2024",Gujarat,Punjab,Punjab,Field,199,4,200,7,Punjab,Shashank Singh,Shubman Gill,Noor Ahmad

18,"April 5,2024",Chennai,Hyderabad,Hyderabad,Field,165,5,166,4,Hyderabad,Abhishek Sharma,Aiden Markram,Moeen Ali

19,"April 6,2024",Banglore,Rajasthan,Rajasthan,Field,183,3,189,4,Rajasthan,Jos Buttler,Virat Kohli,Reece Topley

20,"April 7,2024",Mumbai,Delhi,Delhi,Field,234,5,205,8,Mumbai,Romario Shepherd,Tristan Stubbs ,Gerald Coetzee

21,"April 7,2024",Lucknow,Gujarat,Lucknow,Bat,163,5,130,10,Lucknow,Yash Thakur,Marcus Stoinis,Yash Thakur

22,"April 8,2024",Kolkata,Chennai,Chennai,Field,137,9,141,3,Chennai,Ravindra Jadeja,Ruturaj Gaikwad,Ravindra Jadeja

23,"April 9,2024",Hyderabad,Punjab,Punjab,Field,182,9,180,6,Hyderabad,Nitish Kumar Reddy,Nitish Kumar Reddy,Arshdeep Singh

24,"April 10,2024",Rajasthan,Gujarat,Gujarat,Field,196,3,199,7,Gujarat,Rashid Khan,Riyan Parag,Kuldeep Sen

25,"April 11,2024",Banglore,Mumbai,Mumbai,Field,196,8,199,3,Mumbai,Jasprit Bumrah,Ishan Kishan,Jasprit Bumrah

26,"April 12,2024",Lucknow,Delhi,Lucknow,Bat,167,7,170,4,Delhi,Kuldeep Yadav,Ayush Badoni,Kuldeep Yadav

27,"April 13,2024",Punjab,Rajasthan,Rajasthan,Field,147,8,152,7,Rajasthan,Shimron Hetmyer,Yashasvi Jaiswal ,Kagiso Rabada

28,"April 14,2024",Lucknow,Kolkata,Kolkata,Field,161,7,162,2,Kolkata,Phil Salt,Phil Salt,Mitchell Starc

29,"April 14,2024",Chennai,Mumbai,Mumbai,Field,206,4,186,6,Chennai,Matheesha Pathirana,Rohit Sharma,Matheesha Pathirana

30,"April 15,2024",Hyderabad,Banglore,Banglore,Field,187,3,262,7,Hyderabad,Travis Head,Travis Head,Pat Cummins

31,"April 16,2024",Kolkata,Rajasthan,Rajasthan,Field,223,6,224,8,Rajasthan,Jos Buttler,Sunil Narine ,Sunil Narine

32,"April 17,2024",Gujarat,Delhi,Delhi,Field,89,10,92,4,Delhi,Rishabh Pant,Rashid Khan ,Mukesh Kumar

33,"April 18,2024",Mumbai,Punjab,Punjab,Field,192,7,183,10,Mumbai,Jasprit Bumrah,Suryakumar Yadav,Jasprit Bumrah

34,"April 19,2024",Chennai,Lucknow,Lucknow,Field,176,6,180,2,Lucknow,KL Rahul,KL Rahul,Krunal Pandya

35,"April 20,2024",Hyderabad,Delhi,Delhi,Field,266,7,199,10,Hyderabad,Travis Head,Travis Head,T Natarajan

36,"April 21,2024",Kolkata,Banglore,Banglore,Field,222,6,221,10,Kolkata,Andre Russell,Will Jacks ,Andre Russell

37,"April 21,2024",Punjab,Gujarat,Punjab,Bat,142,10,146,7,Gujarat,Sai Kishore,Rahul Tewatia,Sai Kishore

38,"April 22,2024",Mumbai,Rajasthan,Mumbai,Bat,179,9,183,1,Rajasthan,Sandeep Sharma,Yashasvi Jaiswal ,Sandeep Sharma

39,"April 23,2024",Chennai,Lucknow,Lucknow,Field,210,4,213,4,Lucknow,Marcus Stoinis,Marcus Stoinis,Matheesha Pathirana

40,"April 24,2024",Delhi,Gujarat,Gujarat,Field,224,4,220,8,Delhi,Rishabh Pant,Rishabh Pant,Sandeep Warrier

41,"April 25,2024",Banglore,Hyderabad,Banglore,Bat,206,7,171,8,Banglore,Rajat Patidar,Virat Kohli,Jaydev Unadkat

42,"April 26,2024",Kolkata,Punjab,Punjab,Field,261,6,262,2,Punjab,Jonny Bairstow,Jonny Bairstow,Arshdeep Singh

43,"April 27,2024",Delhi,Mumbai,Mumbai,Field,257,4,247,9,Delhi,Jake Fraser-McGurk,Jake Fraser-McGurk,Rasikh Salam

44,"April 27,2024",Lucknow,Rajasthan,Rajasthan,Field,196,5,199,3,Rajasthan,Sanju Samson,KL Rahul,Sandeep Sharma

45,"April 28,2024",Gujarat,Banglore,Banglore,Field,200,3,206,1,Banglore,Will Jacks,Will Jacks,Swapnil Singh

46,"April 28,2024",Chennai,Hyderabad,Hyderabad,Field,212,3,134,10,Chennai,Ruturaj Gaikwad,Ruturaj Gaikwad,Tushar Deshpande

47,"April 29,2024",Delhi,Kolkata,Delhi,Bat,153,9,157,3,Kolkata,Varun Chakravarthy,Phil Salt,Varun Chakravarthy

48,"April 30,2024",Mumbai,Lucknow,Lucknow,Field,144,7,145,6,Lucknow,Marcus Stoinis,Marcus Stoinis,Hardik Pandya

49,"May 1,2024",Chennai,Punjab,Punjab,Field,162,7,163,3,Punjab,Harpreet Brar,Ruturaj Gaikwad,Rahul Chahar

50,"May 2,2024",Hyderabad,Rajasthan,Hyderabad,Bat,201,3,200,7,Hyderabad,Bhuvneshwar Kumar,Riyan Parag ,Bhuvneshwar Kumar

51,"May 3,2024",Kolkata,Mumbai,Mumbai,Field,169,10,145,10,Kolkata,Venkatesh Iyer,Venkatesh Iyer,Mitchell Starc

52,"May 4,2024",Gujarat,Banglore,Banglore,Field,147,10,152,6,Banglore,Mohammed Siraj,Faf du Plessis,Josh Little

53,"May 5,2024",Chennai,Punjab,Punjab,Field,167,9,139,9,Chennai,Ravindra Jadeja,Ravindra Jadeja,Ravindra Jadeja

54,"May 5,2024",Kolkata,Lucknow,Lucknow,Field,235,6,137,10,Kolkata,Sunil Narine,Sunil Narine,Harshit Rana

55,"May 6,2024",Hyderabad,Mumbai,Mumbai,Field,173,8,174,3,Mumbai,Suryakumar Yadav,Suryakumar Yadav,Hardik Pandya

56,"May 7,2024",Delhi,Rajasthan,Rajasthan,Field,221,8,201,8,Delhi,Kuldeep Yadav,Sanju Samson,Ravichandran Ashwin

57,"May 8,2024",Lucknow,Hyderabad,Lucknow,Bat,165,4,167,0,Hyderabad,Travis Head,Travis Head,Bhuvneshwar Kumar

58,"May 9,2024",Banglore,Punjab,Punjab,Field,241,7,181,10,Banglore,Virat Kohli,Virat Kohli,Harshal Patel

59,"May 10,2024",Gujarat,Chennai,Chennai,Field,231,3,196,8,Gujarat,Shubman Gill,Shubman Gill,Mohit Sharma

60,"May 11,2024",Kolkata,Mumbai,Mumbai,Field,157,7,139,8,Kolkata,Varun Chakravarthy,Venkatesh Iyer,Varun Chakravarthy

61,"May 12,2024",Rajasthan,Chennai,Rajasthan,Bat,141,5,145,5,Chennai,Simarjeet Singh,Riyan Parag,Simarjeet Singh

62,"May 12,2024",Banglore,Delhi,Delhi,Field,187,9,140,10,Banglore,Cameron Green,Axar Patel,Yash Dayal

63,"May 13,2024",Gujarat,Kolkata,No Toss,None,0,0,0,0,Abandoned,None,None,None

64,"May 14,2024",Delhi,Lucknow,Lucknow,Field,208,4,189,9,Delhi,Ishant Sharma,Nicholas Pooran,Ishant Sharma

65,"May 15,2024",Rajasthan,Punjab,Rajasthan,Bat,144,9,145,5,Punjab,Sam Curran,Sam Curran,Rahul Chahar

66,"May 16,2024",Hyderabad,Gujarat,No Toss,None,0,0,0,0,Abandoned,None,None,None

67,"May 17,2024",Lucknow,Mumbai,Mumbai,Field,214,6,196,6,Lucknow,Nicholas Pooran,Nicholas Pooran,Nuwan Thushara

68,"May 18,2024",Banglore,Chennai,Chennai,Field,218,5,191,7,Banglore,Faf du Plessis,Rachin Ravindra,Yash Dayal

69,"May 19,2024",Punjab,Hyderabad,Punjab,Bat,214,5,215,6,Hyderabad,Abhishek Sharma,Prabhsimran Singh,T Natarajan

70,"May 19,2024",Rajasthan,Kolkata,Kolkata,None,0,0,0,0,Abandoned,None,None,None

71,"May 21,2024",Hyderabad,Kolkata,Hyderabad,Bat,159,10,164,2,Kolkata,Mitchell Starc,Shreyas Iyer,Mitchell Starc

72,"May 22,2024",Banglore,Rajasthan,Rajasthan,Field,172,8,174,6,Rajasthan,Ravichandran Ashwin,Yashasvi Jaiswal,Avesh Khan

73,"May 24,2024",Hyderabad,Rajasthan,Rajasthan,Field,175,9,139,7,Hyderabad,Shahbaz Ahmed,Dhruv Jurel ,Shahbaz Ahmed

74,"May 26,2024",Hyderabad,Kolkata,Hyderabad,Bat,113,10,114,2,Kolkata,Mitchell Starc,Venkatesh Iyer,Andre Russell

In [3]:
import pandas as pd
df=pd.read_csv(r"C:\Users\gnana\Downloads\ipl2024 Matches.csv")
df

,id,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts
0,1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman
1,2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav
2,3,"March 23,2024",Kolkata,Hyderabad,Hyderabad,Field,208,7,204,7,Kolkata,Andre Russell,Andre Russell,T Natarajan
3,4,"March 24,2024",Rajasthan,Lucknow,Rajasthan,Bat,193,4,173,6,Rajasthan,Sanju Samson,Sanju Samson,Trent Boult
4,5,"March 24,2024",Gujarat,Mumbai,Mumbai,Field,168,6,162,9,Gujarat,Sai Sudharsan,Dewald Brevis,Jasprit Bumrah
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,70,"May 19,2024",Rajasthan,Kolkata,Kolkata,NaN,0,0,0,0,Abandoned,NaN,NaN,NaN
70,71,"May 21,2024",Hyderabad,Kolkata,Hyderabad,Bat,159,10,164,2,Kolkata,Mitchell Starc,Shreyas Iyer,Mitchell Starc
71,72,"May 22,2024",Banglore,Rajasthan,Rajasthan,Field,172,8,174,6,Rajasthan,Ravichandran Ashwin,Yashasvi Jaiswal,Avesh Khan
72,73,"May 24,2024",Hyderabad,Rajasthan,Rajasthan,Field,175,9,139,7,Hyderabad,Shahbaz Ahmed,Dhruv Jurel,Shahbaz Ahmed
73,74,"May 26,2024",Hyderabad,Kolkata,Hyderabad,Bat,113,10,114,2,Kolkata,Mitchell Starc,Venkatesh Iyer,Andre Russell

In [4]:
df.head()

,id,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts
0,1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman
1,2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav
2,3,"March 23,2024",Kolkata,Hyderabad,Hyderabad,Field,208,7,204,7,Kolkata,Andre Russell,Andre Russell,T Natarajan
3,4,"March 24,2024",Rajasthan,Lucknow,Rajasthan,Bat,193,4,173,6,Rajasthan,Sanju Samson,Sanju Samson,Trent Boult
4,5,"March 24,2024",Gujarat,Mumbai,Mumbai,Field,168,6,162,9,Gujarat,Sai Sudharsan,Dewald Brevis,Jasprit Bumrah

In [5]:
df.tail()

,id,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts
69,70,"May 19,2024",Rajasthan,Kolkata,Kolkata,NaN,0,0,0,0,Abandoned,NaN,NaN,NaN
70,71,"May 21,2024",Hyderabad,Kolkata,Hyderabad,Bat,159,10,164,2,Kolkata,Mitchell Starc,Shreyas Iyer,Mitchell Starc
71,72,"May 22,2024",Banglore,Rajasthan,Rajasthan,Field,172,8,174,6,Rajasthan,Ravichandran Ashwin,Yashasvi Jaiswal,Avesh Khan
72,73,"May 24,2024",Hyderabad,Rajasthan,Rajasthan,Field,175,9,139,7,Hyderabad,Shahbaz Ahmed,Dhruv Jurel,Shahbaz Ahmed
73,74,"May 26,2024",Hyderabad,Kolkata,Hyderabad,Bat,113,10,114,2,Kolkata,Mitchell Starc,Venkatesh Iyer,Andre Russell

In [8]:
df.shape

(74, 14)